### ISSUE TITLE
type hint

### ISSUE THREAD

**Issue by eggplants** [oxigraph/oxrdflib#20]
```
foo.py:28: error: Call to untyped function "open"
in typed context  [no-untyped-call]
            graph.open("bar", create=True)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Tpt** [comment]
@eggplants Hi! It's because rdflib does not provide type hints yet in its released version. They are currently [working on it](https://github.com/RDFLib/rdflib/commit/256e9a2d2bf9800d1e29f03e22b0ac324d28119c) and I hope they will release a new version with them soon. Sadly, there is nothing I can do on oxrdflib side.

**Comment by eggplants** [comment]
Sorry, and Thank you for answering my silly issue! And yes, the above mypy error was fixed with rdflib latest version including https://github.com/RDFLib/rdflib/commit/256e9a2d2bf9800d1e29f03e22b0ac324d28119c.
